# Generated by Django 2.1.7 on 2019-07-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190722_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEightHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFiveheading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFourHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOneHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSevenHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSixHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceThreeHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTwoHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='aboutussectiononeheading',
            old_name='content',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='aboutussectiontwoheading',
            old_name='content',
            new_name='heading',
        ),
    ]
