# Generated by Django 2.1.7 on 2019-07-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20190722_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='aboutusquote',
            name='content',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aboutussectionone',
            name='content',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='aboutussectiononeheading',
            name='heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aboutussectiontwo',
            name='content',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='aboutussectiontwoheading',
            name='heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serviceeightheading',
            name='heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicefiveheading',
            name='heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicefourheading',
            name='heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serviceoneheading',
            name='heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicesevenheading',
            name='heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicesixheading',
            name='heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicethreeheading',
            name='heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicetwoheading',
            name='heading',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
